# Generated by Django 5.1.1 on 2024-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_quest_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='quest',
            name='date published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
