# Generated by Django 5.1.1 on 2024-09-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_remove_quest_pub_date_quest_date_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='date published',
            new_name='pub_date',
        ),
    ]
