# Generated by Django 5.1.1 on 2024-09-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_rename_date_published_quest_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
